# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sequel_oracle_extensions"
  s.version = "0.7.0.rc0"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joe Khoobyar"]
  s.date = "2012-09-10"
  s.description = "Oracle extensions for Sequel, including MERGE statements, optimizer hints, and schema extensions."
  s.email = "joe@ankhcraft.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/sequel/oracle_extensions.rb",
    "lib/sequel/oracle_extensions/hints.rb",
    "lib/sequel/oracle_extensions/merge.rb",
    "lib/sequel/oracle_extensions/schemata.rb",
    "lib/sequel_oracle_extensions.rb",
    "sequel_oracle_extensions.gemspec",
    "spec/sequel/oracle_extensions/hints_spec.rb",
    "spec/sequel/oracle_extensions/merge_spec.rb",
    "spec/sequel/oracle_extensions/schemata_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/joekhoobyar/sequel_oracle_extensions"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Oracle MERGE, optimizer hints, and schema extensions for Sequel"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel>, [">= 3.39"])
      s.add_runtime_dependency(%q<ruby-oci8>, [">= 2.1"])
      s.add_development_dependency(%q<rspec>, [">= 2.0"])
    else
      s.add_dependency(%q<sequel>, [">= 3.39"])
      s.add_dependency(%q<ruby-oci8>, [">= 2.1"])
      s.add_dependency(%q<rspec>, [">= 2.0"])
    end
  else
    s.add_dependency(%q<sequel>, [">= 3.39"])
    s.add_dependency(%q<ruby-oci8>, [">= 2.1"])
    s.add_dependency(%q<rspec>, [">= 2.0"])
  end
end

